apiVersion: apps/v1
kind: Deployment
metadata:
  name: bandicoot-prod
  labels:
    app: bandicoot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bandicoot
      env: prod
      ver: "2"
  template:
    metadata:
      labels:
        app: bandicoot
        env: prod
        ver: "2"
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:green
        ports:
        - containerPort: 8080

